version: '3'
services:
  express:
    image: mihilt/waf-server:latest
    build:
      context: ./
      dockerfile: ./express.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/waf-development?retryWrites=true&w=majority
      - REDIS_HOST=redis
    command: npm run docker:start

  mongodb:
    image: mongo
    volumes:
      - ~/docker-data/mongodb:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mongodb_data:
