version: '3'
services:
  express:
    image: mihilt/waf-server:latest
    build:
      context: ./
      dockerfile: ./express.Dockerfile
    volumes:
      - ~/docker-data/waf/uploads:/app/public/uploads
      - ~/docker-data/waf/logs:/app/logs
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://${MONGO_WAF_USERNAME}:${MONGO_WAF_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?retryWrites=true&w=majority
      - REDIS_HOST=redis
    command: npm run docker:start

  mongodb:
    image: mongo
    volumes:
      - ~/docker-data/waf/mongodb:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mongodb_data:
